# Generated by Django 5.0.3 on 2025-08-13 11:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_options_empleado_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=django_ckeditor_5.fields.CKEditor5Field(default='texto', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
