# Generated by Django 5.0.3 on 2025-09-08 05:53

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='hoja_vida',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Hoja de Vida'),
        ),
    ]
